server:
  port: 8080
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  metrics:
    export:
      statsd:
        enabled: false
